import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import UserIcon from "../assets/User.svg";
import PanelIcon from "../assets/Panel.svg";
import SearchBar from "../assets/search2.svg";
import Notification from "../assets/Alert.svg";
const TopBar = () => {
    return (_jsxs("div", { className: "w-full flex justify-between items-center px-4 py-2 bg-white border-b-2 border-gray-200 text-sm", children: [_jsxs("div", { className: "font-semibold flex items-center gap-2", children: [_jsx("img", { alt: "Sidebar Icon", className: "px-2", src: PanelIcon }), _jsx("span", { className: "text-[#afafaf] cursor-pointer hover:underline", children: "WorkSpace" }), _jsx("span", { className: "text-[#afafaf]", children: '>' }), _jsx("span", { className: "text-[#afafaf] cursor-pointer hover:underline", children: "Folder 2" }), _jsx("span", { className: "text-[#afafaf]", children: '>' }), _jsx("span", { className: "cursor-pointer hover:underline", children: "Spreadsheet 3" }), _jsx("span", { className: "text-[#afafaf] text-lg tracking-wider ml-1 -translate-y-1", style: { lineHeight: 1 }, children: "..." })] }), _jsxs("div", { className: "flex items-center gap-2 pr-3", children: [_jsxs("div", { className: "bg-[#F6F6F6] flex items-center gap-2 p-2.5 rounded-lg text-gray-500 w-[150px]", children: [_jsx("img", { src: SearchBar, alt: "", className: 'w-5 h-5' }), _jsx("input", { placeholder: "Search within sheet", className: "text-xs bg-transparent outline-none placeholder:text-gray-400 w-[105px]", type: "text" })] }), _jsx("img", { alt: "Notifications", className: "cursor-pointer", src: Notification }), _jsx("img", { alt: "Profile", className: "w-8 h-8 bg-gray-300 rounded-full cursor-pointer", src: UserIcon }), _jsxs("div", { className: "flex flex-col leading-tight cursor-pointer", children: [_jsx("div", { className: "text-xs", children: "John Doe" }), _jsx("div", { className: "text-[#afafaf] text-[10px]", children: "john.doe..." })] })] })] }));
};
export default TopBar;
